### PR TITLE
Added support for Scale prop to the sketchpad.

### PR DESCRIPTION
**Pull request by samridhgupta**
Hey everyone,

Here's a pull request for the implementation of Scale prop.

Fixed issue: When the canvas is scaled and moved, the point you touch will be different from the point it really paints. It behaves like the gesture is also transformed.

Updated the Readme for same.

### CODE REVIEW

**Comment by creambyemute** [comment]
@samridhgupta Hey, thanks for the PR. I'll have a look at it and probably merge it, shouldn't have any side-effects as much as I see.

**Comment by samridhgupta** [comment]
> @samridhgupta Hey, thanks for the PR. I'll have a look at it and probably merge it, shouldn't have any side-effects as much as I see.

Thanks @creambyemute 
No side-effects on current implementation with this addition

**Comment by samridhgupta** [comment]
Would it be possible to merge this PR soon,
I need this fix as i need to use the addShape functionality from your repo

**Comment by creambyemute** [comment]
@samridhgupta Merged

**Comment by samridhgupta** [comment]
thanks @creambyemute

**Pull request merged**
